name: Merge Request CI Pipeline

on:
  pull_request: # Déclenché pour les pull requests
    types:
      - opened
      - synchronize # Pour exécuter à chaque mise à jour de la pull request
      - reopened

permissions:
  contents: read

jobs:
  # Job pour construire le frontend
  build_frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Spécifiez la version de Node.js

    - name: Install dependencies and build frontend
      run: |
        npm install
        npm run build
      working-directory: ./frontend # Chemin vers le frontend

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: ./frontend/build # Stocke les artefacts du frontend pour un examen manuel si nécessaire

  # Job pour construire le backend
  build_backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0' # Spécifiez la version de .NET

    - name: Restore and build backend
      run: |
        dotnet restore
        dotnet build --configuration Release
      working-directory: ./backend # Chemin vers le backend

    - name: Publish backend
      run: |
        dotnet publish -c Release --output ./publish
      working-directory: ./backend

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: backend-publish
        path: ./backend/publish # Stocke les artefacts du backend pour un examen manuel si nécessaire

  # Job pour vérifier la syntaxe (optionnel)
  lint_code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Lint frontend
      run: npm run lint
      working-directory: ./frontend

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    - name: Lint backend
      run: dotnet format --check # Vérifie le formatage du code backend
