name: CI for Merge Requests

on:
  pull_request:  # Déclenchement lors de la création ou modification d'une Pull Request

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build React app
        run: |
          cd frontend
          npm run build

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0  # Spécifie la version de .NET

      - name: Restore and build .NET app
        run: |
          cd backend
          dotnet restore
          dotnet build

      - name: Publish .NET app
        run: |
          cd backend
          dotnet publish -c Release
